#Week-1

In [39]:
import numpy as np

In [40]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
#getting diagonal elements
print(matrix.diagonal())

[1 5 9]


In [42]:
#printing elements above and below principal diagonal
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=-1))

[2 6]
[4 8]


In [43]:
#trace of a matrix
print(matrix.trace())

15


In [44]:
#eigen values and eigen vectors
eva,eve = np.linalg.eig(matrix)
print(eva)
print(eve)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [45]:
#dot product of two vectors
v1 = np.array([2,4,3])
v2 = np.array([9,8,6])
print(np.dot(v1,v2))
print(v1@v2)
print(v1*v2)

68
68
[18 32 18]


In [46]:
#addition,subtraction and multiplication of two matrices
m1 = np.array([[1,2,3],[4,5,6],[3,6,9]])
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(m1+m2) #np.add(m1,m2)
print(m1-m2) #np.subtract(m1,m2)
print(m1*m2)#np.multiply(m1,m2)

[[10 10 10]
 [10 10 10]
 [ 6  8 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 0  4  8]]
[[ 9 16 21]
 [24 25 24]
 [ 9 12  9]]


#Another way

In [47]:
print(np.add(m1,m2))
print(np.subtract(m1,m2))
print(np.multiply(m1,m2))

[[10 10 10]
 [10 10 10]
 [ 6  8 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 0  4  8]]
[[ 9 16 21]
 [24 25 24]
 [ 9 12  9]]


#Random values

In [48]:
ran = np.random.seed(1)
print(ran)
print(np.random.randint(0,11,3))
print(np.random.randint(0,11,5))
print(np.random.randint(100,size=100))
print(np.random.randint(100,size=5))

None
[5 8 9]
[5 0 0 1 7]
[ 6 25 50 20 18 84 11 28 29 14 50 68 87 87 94 96 86 13  9  7 63 61 22 57
  1  0 60 81  8 88 13 47 72 30 71  3 70 21 49 57  3 68 24 43 76 26 52 80
 41 82 15 64 68 25 98 87  7 26 25 22  9 67 23 27 37 57 83 38  8 32 34 10
 23 15 87 25 71 92 74 62 46 32 88 23 55 65 77  3  0 77  6 52 85 70  2 76
 91 21 75  7]
[77 72 75 76 43]


In [49]:
#random numbers from array
x=np.random.choice([1,3,5,6])
y=np.random.choice([1,3,5,7,9],size=(2,4))
print(x)
print(y)

1
[[9 9 3 1]
 [9 5 1 5]]


In [50]:
np.random.normal(size=(2,3))

array([[ 0.28558733,  0.88514116, -0.75439794],
       [ 1.25286816,  0.51292982, -0.29809284]])

#Week-2

In [56]:
#Creating a DataFrame
import pandas as pd

In [57]:
df = pd.DataFrame(np.random.randn(3,5))
print(df)

          0         1         2         3         4
0  0.361236 -0.937864 -1.385656 -0.338881 -0.179255
1 -0.240947 -0.247699 -0.168520  0.573709 -0.956773
2 -0.651523  0.719275  1.234399 -0.266468  1.564649
